<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container76cSTvb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container76cSTvb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container76cSTvb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container76cSTvb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container76cSTvb\App_KernelDevDebugContainer([
    'container.build_hash' => '76cSTvb',
    'container.build_id' => 'acb66108',
    'container.build_time' => 1625929778,
], __DIR__.\DIRECTORY_SEPARATOR.'Container76cSTvb');
